export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const BOARD_FETCHED = 'BOARD_FETCHED';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';

export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';

export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
